# Exception is a event which disrupts normal flow of program. 
# handled in run-time

# prin("Hello World") error

# i = 1/0 Exception

# Try - catch block